global:
  resolve_timeout: 1m

route:
  receiver: 'telegram'
  group_by: ['alertname','instance']
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 1h

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: '${TELEGRAM_BOT_TOKEN}'
    chat_id: ${ALERTS_CHAT_ID}
    parse_mode: 'HTML'
    message: |-
      <b>{{ .Status | toUpper }}</b> — {{ .CommonLabels.alertname }}
      {{ range .Alerts -}}
      • <b>{{ .Labels.instance }}</b> — {{ .Annotations.summary }}
        {{ .Annotations.description }}
      {{ end }}
