global:
  resolve_timeout: 1m

route:
  receiver: 'telegram'
  group_by: ['alertname','instance']
  group_wait: ${AM_GROUP_WAIT}
  group_interval: ${AM_GROUP_INTERVAL}
  repeat_interval: ${AM_REPEAT_INTERVAL}

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: ${ALERTS_CHAT_ID}
    parse_mode: 'HTML'
    message: |-
      <b>{{ .Status | toUpper }}</b> — {{ .CommonLabels.alertname }}
      {{ range .Alerts -}}
      • <b>{{ .Labels.instance }}</b> — {{ .Annotations.summary }}
        {{ .Annotations.description }}
      {{ end }}
