services:
  bot:
    container_name: faro_bot
    build: ./bot
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - ./bot:/app:ro
      - /proc:/host/proc:ro
      - /:/host:ro
    depends_on:
      - prometheus
      - alertmanager

  prometheus:
    container_name: faro_prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - prom_data:/prometheus
      - ./prometheus/entrypoint.sh:/entrypoint.sh:ro
      - ./prometheus/prometheus.yml.tmpl:/etc/prometheus/prometheus.yml.tmpl:ro
      - ./prometheus/rules/faro-core.yml.tmpl:/etc/prometheus/rules/faro-core.yml.tmpl:ro
    command: ["/bin/sh", "/entrypoint.sh"]

  alertmanager:
    container_name: faro_alertmanager
    image: prom/alertmanager:latest
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - am_data:/alertmanager
      - ./alertmanager/entrypoint.sh:/entrypoint.sh:ro
      - ./alertmanager/alertmanager.yml.tmpl:/etc/alertmanager/alertmanager.yml.tmpl:ro
    command: ["/bin/sh", "/entrypoint.sh"]

  node-exporter:
    container_name: faro_node_exporter
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--web.listen-address=127.0.0.1:9100'

volumes:
  prom_data:
  am_data:
