services:
  bot:
    container_name: faro_bot
    build: ./bot
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - ./bot:/app:ro
      - /proc:/host/proc:ro
      - /:/host:ro
    depends_on:
      prometheus:
        condition: service_healthy
      alertmanager:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "print('ok')"]
      interval: 30s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: faro_prometheus
    restart: unless-stopped
    env_file: .env
    network_mode: host
    user: "root"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - prom_data:/prometheus
      - ./prometheus/entrypoint.sh:/entrypoint.sh:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml.src:ro
      - ./prometheus/rules/faro-core.yml:/etc/prometheus/rules/faro-core.yml.src:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9090/-/ready"]
      interval: 15s
      timeout: 5s
      retries: 10

  alertmanager:
    image: prom/alertmanager:latest
    container_name: faro_alertmanager
    restart: unless-stopped
    env_file: .env
    network_mode: host
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - am_data:/alertmanager
      - ./alertmanager/entrypoint.sh:/entrypoint.sh:ro
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml.src:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9093/-/healthy"]
      interval: 15s
      timeout: 5s
      retries: 10

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: faro_node_exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--web.listen-address=${NODE_EXPORTER_HOSTPORT}'

volumes:
  prom_data:
  am_data:
